#!/bin/sh

# build dir
BD="."

test -d "$BD" || exit 1
rm -rf iso dnq.iso
mkdir -p iso/boot/grub
cp "$BD/mkldr/mkldr" iso/boot

cat <<EOT >iso/boot/grub/grub.cfg
set timeout=0
set default=0
menuentry "DNQ Test" {
    search --file --set root --no-floppy /boot/mkldr
    multiboot /boot/mkldr
}
EOT

grub2-mkrescue -o dnq.iso iso
rm -rf iso
