#!/usr/bin/perl -w

use strict;

die() unless scalar(@ARGV) == 1;

binmode(STDIN);
my ($buf, $data, $n);
while (($n = read STDIN, $data, 65536) != 0) {
  $buf .= $data;
}
die() unless $buf;

my $cnt = 0;
my $dlen = length($buf);
print "/* autogenerated: ${dlen} bytes */\n";
print "unsigned char ${ARGV[0]}[] = {\n";

for my $i (0..$dlen-2) {
  print "\t" if ($cnt == 0);
  printf "0x%02x, ", ord(substr($buf,$i,1));
  $cnt += 1;
  if ($cnt > 9) {
    print "\n";
    $cnt = 0;
  }
}
printf "0x%02x", ord(substr($buf,$dlen-1,1));
print "\n};\n\n";

print "unsigned ${ARGV[0]}_sz = sizeof(${ARGV[0]});\n";

#my @s = unpack("a2", $buf);
#for (@s) {
#  print $_, " ";
#}
